const arabicLocations = {
  السعودية: [
    "الرياض",
    "جدة",
    "مكة",
    "المدينة المنورة",
    "الدمام",
    "الخبر",
    "تبوك",
    "القصيم",
    "حائل",
    "جازان",
  ],
  مصر: [
    "القاهرة",
    "الإسكندرية",
    "الجيزة",
    "الأقصر",
    "أسوان",
    "بورسعيد",
    "السويس",
    "طنطا",
    "دمنهور",
    "المنصورة",
  ],
  الأردن: [
    "عمان",
    "إربد",
    "الزرقاء",
    "العقبة",
    "السلط",
    "الكرك",
    "الطفيلة",
    "جرش",
    "مادبا",
    "مأدبا",
  ],
  المغرب: [
    "الرباط",
    "الدار البيضاء",
    "مراكش",
    "فاس",
    "طنجة",
    "أكادير",
    "وجدة",
    "تطوان",
    "القنيطرة",
    "الناظور",
  ],
  الإمارات: [
    "أبو ظبي",
    "دبي",
    "الشارقة",
    "العين",
    "رأس الخيمة",
    "الفجيرة",
    "عجمان",
    "أم القيوين",
    "دبا",
    "الخور",
  ],
  الجزائر: [
    "الجزائر",
    "وهران",
    "قسنطينة",
    "عنابة",
    "سطيف",
    "تيبازة",
    "باتنة",
    "تبسة",
    "الجلفة",
    "تيارت",
  ],
  البحرين: [
    "المنامة",
    "المحرق",
    "الرفاع",
    "عيسى",
    "سار",
    "جزر حوار",
    "جزر أمواج",
    "جزر سلمى",
    "العالي",
    "الجنوبية",
  ],
  جيبوتي: [
    "جيبوتي",
    "أرباب",
    "بلتصر",
    "دادا",
    "عطبرة",
    "حزيمة",
    "ذاكوا",
    "تاماريس",
    "كادربلي",
    "دمره",
  ],
  الصومال: [
    "مقديشو",
    "هرجيسا",
    "بوساسو",
    "غارووي",
    "كيسمايو",
    "مركا",
    "جاراوي",
    "بلدوين",
    "هغوير",
    "بربرة",
  ],
  السودان: [
    "الخرطوم",
    "بحري",
    "أمدرمان",
    "مدني",
    "كسلا",
    "الجنينة",
    "الفاشر",
    "نيالا",
    "سنار",
    "دنقلا",
  ],
  تونس: [
    "تونس",
    "صفاقس",
    "سوسة",
    "القيروان",
    "القصرين",
    "المهدية",
    "قفصة",
    "مدنين",
    "بنزرت",
    "بن عروس",
  ],
  العراق: [
    "بغداد",
    "البصرة",
    "الموصل",
    "أربيل",
    "كركوك",
    "النجف",
    "كربلاء",
    "دهوك",
    "السليمانية",
    "الحلة",
  ],
  الكويت: [
    "مدينة الكويت",
    "الأحمدي",
    "الفروانية",
    "الجهراء",
    "حولي",
    "مبارك الكبير",
    "دولي",
    "صباحية",
    "الشويخ",
    "الفحيحيل",
  ],
  لبنان: [
    "بيروت",
    "صيدا",
    "طرابلس",
    "جبيل",
    "زحلة",
    "بعبدا",
    "رأس بيروت",
    "صور",
    "النبطية",
    "بشري",
  ],
  ليبيا: [
    "طرابلس",
    "بنغازي",
    "مصراتة",
    "الزاوية",
    "سبها",
    "الخمس",
    "درنة",
    "غريان",
    "الجفرة",
    "البيضاء",
  ],
  موريتانيا: [
    "نواكشوط",
    "نواديبو",
    "كيفة",
    "ألاك",
    "بوتلميت",
    "روصو",
    "أطار",
    "أمبود",
    "الشنقيط",
    "النيل",
  ],
  عمان: [
    "مسقط",
    "صلالة",
    "نزوى",
    "السيب",
    "الرستاق",
    "صور",
    "خصب",
    "عبري",
    "سمائل",
    "الخابورة",
  ],
  فلسطين: [
    "القدس",
    "رام الله",
    "بيت لحم",
    "نابلس",
    "الخليل",
    "جنين",
    "طولكرم",
    "قلقيلية",
    "طوباس",
    "أريحا",
  ],
  قطر: [
    "الدوحة",
    "الوكرة",
    "الريان",
    "الخور",
    "الزعترة",
    "مسيمير",
    "الشحانية",
    "الظعاين",
    "الدفنة",
    "الخور",
  ],
  سوريا: [
    "دمشق",
    "حلب",
    "حمص",
    "حماة",
    "اللاذقية",
    "دير الزور",
    "الرقة",
    "إدلب",
    "القنيطرة",
    "السويداء",
  ],
  اليمن: [
    "صنعاء",
    "عدن",
    "تعز",
    "الحديدة",
    "المكلا",
    "حضرموت",
    "إب",
    "ريمة",
    "ذمار",
    "الحوطة",
  ],
  "جزر القمر": [
    "موروني",
    "ميلي",
    "مبوانا",
    "شوالا",
    "باندزوني",
    "شيمبواني",
    "موتساما",
    "بامبانزا",
    "دزياني",
    "موتيندو",
  ],
  "السعودية الجنوبية": [
    "جازان",
    "نجران",
    "الباحة",
    "عسير",
    "القنفذة",
    "تثليث",
    "ظهران الجنوب",
    "بيشة",
    "بللسمر",
    "العيدابي",
  ],
};

const englishLocations = {
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Tabuk",
    "Qassim",
    "Hail",
    "Jazan",
  ],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Luxor",
    "Aswan",
    "Port Said",
    "Suez",
    "Tanta",
    "Damanhur",
    "Mansoura",
  ],
  Jordan: [
    "Amman",
    "Irbid",
    "Zarqa",
    "Aqaba",
    "Salt",
    "Karak",
    "Tafileh",
    "Jerash",
    "Madaba",
    "Ma'an",
  ],
  Morocco: [
    "Rabat",
    "Casablanca",
    "Marrakech",
    "Fes",
    "Tangier",
    "Agadir",
    "Oujda",
    "Tetouan",
    "Kenitra",
    "Fquih Ben Salah",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Al Ain",
    "Ras Al Khaimah",
    "Fujairah",
    "Ajman",
    "Umm Al Quwain",
    "Dibba",
    "Al Khawr",
  ],
  Algeria: [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Setif",
    "Tipaza",
    "Batna",
    "Tebessa",
    "Djelfa",
    "Tiaret",
  ],
  Bahrain: [
    "Manama",
    "Muharraq",
    "Riffa",
    "Isa Town",
    "Saar",
    "Hawar Islands",
    "Amwaj Islands",
    "Salma Islands",
    "Al Ali",
    "Southern",
  ],
  Djibouti: [
    "Djibouti",
    "Arta",
    "Balbala",
    "Dada",
    "Obock",
    "Ali Sabieh",
    "Tadjoura",
    "Kardibli",
    "Tamaris",
    "Dikhil",
  ],
  Somalia: [
    "Mogadishu",
    "Hargeisa",
    "Bosaso",
    "Garowe",
    "Kismayo",
    "Marka",
    "Jarrahi",
    "Baldwin",
    "Heguir",
    "Berbera",
  ],
  Sudan: [
    "Khartoum",
    "Bahri",
    "Omdurman",
    "Madani",
    "Kassala",
    "Al Geneina",
    "Al Fasher",
    "Nyala",
    "Sennar",
    "Dongola",
  ],
  Tunisia: [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Kasserine",
    "Mahdia",
    "Gafsa",
    "Medenine",
    "Bizerte",
    "Ben Arous",
  ],
  Iraq: [
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Kirkuk",
    "Najaf",
    "Karbala",
    "Duhok",
    "Sulaymaniyah",
    "Hilla",
  ],
  Kuwait: [
    "Kuwait City",
    "Ahmadi",
    "Farwaniya",
    "Jahra",
    "Hawalli",
    "Mubarak Al-Kabeer",
    "Dasman",
    "Sabah Al Salem",
    "Shuwaikh",
    "Fahaheel",
  ],
  Lebanon: [
    "Beirut",
    "Sidon",
    "Tripoli",
    "Byblos",
    "Zahle",
    "Baabda",
    "Ras Beirut",
    "Tyre",
    "Nabatieh",
    "Bsharri",
  ],
  Libya: [
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Zawiya",
    "Sebha",
    "Al Khums",
    "Derna",
    "Gharian",
    "Jufra",
    "Bayda",
  ],
  Mauritania: [
    "Nouakchott",
    "Nouadhibou",
    "Kiffa",
    "Aleg",
    "Boutilimit",
    "Rosso",
    "Atar",
    "Amojjar",
    "Chinguetti",
    "Nile",
  ],
  Oman: [
    "Muscat",
    "Salalah",
    "Nizwa",
    "Seeb",
    "Rustaq",
    "Sur",
    "Khasab",
    "Ibri",
    "Sohar",
    "Khaburah",
  ],
  Palestine: [
    "Jerusalem",
    "Ramallah",
    "Bethlehem",
    "Nablus",
    "Hebron",
    "Jenin",
    "Tulkarm",
    "Qalqilya",
    "Tubas",
    "Ariha",
  ],
  Qatar: [
    "Doha",
    "Al Wakrah",
    "Al Rayyan",
    "Al Khor",
    "Az Zubarah",
    "Mesaimeer",
    "Al Shahaniya",
    "Al Thakhira",
    "Dafna",
    "Al Khor",
  ],
  Syria: [
    "Damascus",
    "Aleppo",
    "Homs",
    "Hama",
    "Latakia",
    "Deir ez-Zor",
    "Raqqa",
    "Idlib",
    "Quneitra",
    "As-Suwayda",
  ],
  Yemen: [
    "Sana'a",
    "Aden",
    "Taiz",
    "Al Hudaydah",
    "Mukalla",
    "Hadhramaut",
    "Ibb",
    "Raymah",
    "Dhamar",
    "Al Hawtah",
  ],
  Comoros: [
    "Moroni",
    "Mili",
    "Mbouana",
    "Shawalla",
    "Bandzoni",
    "Shimbwani",
    "Moutsama",
    "Bambanza",
    "Dzyani",
    "Motindo",
  ],
  "Southern Saudi Arabia": [
    "Jazan",
    "Najran",
    "Al Bahah",
    "Asir",
    "Al Qunfudhah",
    "Thuluth",
    "Zahran Al Janoub",
    "Bisha",
    "Ballasmar",
    "Al Eidabi",
  ],
};

const countryMap = {
  السعودية: "Saudi Arabia",
  مصر: "Egypt",
  الأردن: "Jordan",
  المغرب: "Morocco",
  الإمارات: "United Arab Emirates",
  الجزائر: "Algeria",
  البحرين: "Bahrain",
  جيبوتي: "Djibouti",
  الصومال: "Somalia",
  السودان: "Sudan",
  تونس: "Tunisia",
  العراق: "Iraq",
  الكويت: "Kuwait",
  لبنان: "Lebanon",
  ليبيا: "Libya",
  موريتانيا: "Mauritania",
  عمان: "Oman",
  فلسطين: "Palestine",
  قطر: "Qatar",
  سوريا: "Syria",
  اليمن: "Yemen",
  "جزر القمر": "Comoros",
  "السعودية الجنوبية": "Southern Saudi Arabia",
};

const cityMap = {
  الرياض: "Riyadh",
  جدة: "Jeddah",
  مكة: "Mecca",
  "المدينة المنورة": "Medina",
  الدمام: "Dammam",
  الخبر: "Khobar",
  تبوك: "Tabuk",
  القصيم: "Qassim",
  حائل: "Hail",
  جازان: "Jazan",
  القاهرة: "Cairo",
  الإسكندرية: "Alexandria",
  الجيزة: "Giza",
  الأقصر: "Luxor",
  أسوان: "Aswan",
  بورسعيد: "Port Said",
  السويس: "Suez",
  طنطا: "Tanta",
  دمنهور: "Damanhur",
  المنصورة: "Mansoura",
  عمان: "Amman",
  إربد: "Irbid",
  الزرقاء: "Zarqa",
  العقبة: "Aqaba",
  السلط: "Salt",
  الكرك: "Karak",
  الطفيلة: "Tafileh",
  جرش: "Jerash",
  مادبا: "Madaba",
  مأدبا: "Ma'an",
  الرباط: "Rabat",
  "الدار البيضاء": "Casablanca",
  مراكش: "Marrakech",
  فاس: "Fes",
  طنجة: "Tangier",
  أكادير: "Agadir",
  وجدة: "Oujda",
  تطوان: "Tetouan",
  القنيطرة: "Kenitra",
  الناظور: "Fquih Ben Salah",
  "أبو ظبي": "Abu Dhabi",
  دبي: "Dubai",
  الشارقة: "Sharjah",
  العين: "Al Ain",
  "رأس الخيمة": "Ras Al Khaimah",
  الفجيرة: "Fujairah",
  عجمان: "Ajman",
  "أم القيوين": "Umm Al Quwain",
  دبا: "Dibba",
  الخور: "Al Khawr",
  الجزائر: "Algiers",
  وهران: "Oran",
  قسنطينة: "Constantine",
  عنابة: "Annaba",
  سطيف: "Setif",
  تيبازة: "Tipaza",
  باتنة: "Batna",
  تبسة: "Tebessa",
  الجلفة: "Djelfa",
  تيارت: "Tiaret",
  المنامة: "Manama",
  المحرق: "Muharraq",
  الرفاع: "Riffa",
  عيسى: "Isa Town",
  سار: "Saar",
  "جزر حوار": "Hawar Islands",
  "جزر أمواج": "Amwaj Islands",
  "جزر سلمى": "Salma Islands",
  العالي: "Al Ali",
  الجنوبية: "Southern",
  جيبوتي: "Djibouti",
  أرباب: "Arta",
  بلتصر: "Balbala",
  دادا: "Dada",
  عطبرة: "Obock",
  حزيمة: "Ali Sabieh",
  ذاكوا: "Tadjoura",
  تاماريس: "Kardibli",
  كادربلي: "Tamaris",
  دمره: "Dikhil",
  مقديشو: "Mogadishu",
  هرجيسا: "Hargeisa",
  بوساسو: "Bosaso",
  غارووي: "Garowe",
  كيسمايو: "Kismayo",
  مركا: "Marka",
  جاراوي: "Jarrahi",
  بلدوين: "Baldwin",
  هغوير: "Heguir",
  بربرة: "Berbera",
  الخرطوم: "Khartoum",
  بحري: "Bahri",
  أمدرمان: "Omdurman",
  مدني: "Madani",
  كسلا: "Kassala",
  الجنينة: "Al Geneina",
  الفاشر: "Al Fasher",
  نيالا: "Nyala",
  سنار: "Sennar",
  دنقلا: "Dongola",
  تونس: "Tunis",
  صفاقس: "Sfax",
  سوسة: "Sousse",
  القيروان: "Kairouan",
  القصرين: "Kasserine",
  المهدية: "Mahdia",
  قفصة: "Gafsa",
  مدنين: "Medenine",
  بنزرت: "Bizerte",
  "بن عروس": "Ben Arous",
  بغداد: "Baghdad",
  البصرة: "Basra",
  الموصل: "Mosul",
  أربيل: "Erbil",
  كركوك: "Kirkuk",
  النجف: "Najaf",
  كربلاء: "Karbala",
  دهوك: "Duhok",
  السليمانية: "Sulaymaniyah",
  الحلة: "Hilla",
  "مدينة الكويت": "Kuwait City",
  الأحمدي: "Ahmadi",
  الفروانية: "Farwaniya",
  الجهراء: "Jahra",
  حولي: "Hawalli",
  "مبارك الكبير": "Mubarak Al-Kabeer",
  دولي: "Dasman",
  صباحية: "Sabah Al Salem",
  الشويخ: "Shuwaikh",
  الفحيحيل: "Fahaheel",
  بيروت: "Beirut",
  صيدا: "Sidon",
  طرابلس: "Tripoli",
  جبيل: "Byblos",
  زحلة: "Zahle",
  بعبدا: "Baabda",
  "رأس بيروت": "Ras Beirut",
  صور: "Tyre",
  النبطية: "Nabatieh",
  بشري: "Bsharri",
  طرابلس: "Tripoli",
  بنغازي: "Benghazi",
  مصراتة: "Misrata",
  الزاوية: "Zawiya",
  سبها: "Sebha",
  الخمس: "Al Khums",
  درنة: "Derna",
  غريان: "Gharian",
  الجفرة: "Jufra",
  البيضاء: "Bayda",
  نواكشوط: "Nouakchott",
  نواديبو: "Nouadhibou",
  كيفة: "Kiffa",
  ألاك: "Aleg",
  بوتلميت: "Boutilimit",
  روصو: "Rosso",
  أطار: "Atar",
  أمبود: "Amojjar",
  الشنقيط: "Chinguetti",
  النيل: "Nile",
  مسقط: "Muscat",
  صلالة: "Salalah",
  نزوى: "Nizwa",
  السيب: "Seeb",
  الرستاق: "Rustaq",
  صور: "Sur",
  خصب: "Khasab",
  عبري: "Ibri",
  سمائل: "Sohar",
  الخابورة: "Khaburah",
  القدس: "Jerusalem",
  "رام الله": "Ramallah",
  "بيت لحم": "Bethlehem",
  نابلس: "Nablus",
  الخليل: "Hebron",
  جنين: "Jenin",
  طولكرم: "Tulkarm",
  قلقيلية: "Qalqilya",
  طوباس: "Tubas",
  أريحا: "Ariha",
  الدوحة: "Doha",
  الوكرة: "Al Wakrah",
  الريان: "Al Rayyan",
  الخور: "Al Khor",
  الزعترة: "Az Zubarah",
  مسيمير: "Mesaimeer",
  الشحانية: "Al Shahaniya",
  الظعاين: "Al Thakhira",
  الدفنة: "Dafna",
  الخور: "Al Khor",
  دمشق: "Damascus",
  حلب: "Aleppo",
  حمص: "Homs",
  حماة: "Hama",
  اللاذقية: "Latakia",
  "دير الزور": "Deir ez-Zor",
  الرقة: "Raqqa",
  إدلب: "Idlib",
  القنيطرة: "Quneitra",
  السويداء: "As-Suwayda",
  صنعاء: "Sana'a",
  عدن: "Aden",
  تعز: "Taiz",
  الحديدة: "Al Hudaydah",
  المكلا: "Mukalla",
  حضرموت: "Hadhramaut",
  إب: "Ibb",
  ريمة: "Raymah",
  ذمار: "Dhamar",
  الحوطة: "Al Hawtah",
  موروني: "Moroni",
  ميلي: "Mili",
  مبوانا: "Mbouana",
  شوالا: "Shawalla",
  باندزوني: "Bandzoni",
  شيمبواني: "Shimbwani",
  موتساما: "Moutsama",
  بامبانزا: "Bambanza",
  دزياني: "Dzyani",
  موتيندو: "Motindo",
  جازان: "Jazan",
  نجران: "Najran",
  الباحة: "Al Bahah",
  عسير: "Asir",
  القنفذة: "Al Qunfudhah",
  تثليث: "Thuluth",
  "ظهران الجنوب": "Zahran Al Janoub",
  بيشة: "Bisha",
  بللسمر: "Ballasmar",
  العيدابي: "Al Eidabi",
};
